# Generated by Django 6.0.7 on 2026-07-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_contactmessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=10)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, help_text='Optional, e.g. Support, Sales', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
            ],
            options={
                'verbose_name_plural': 'Site Contact Info',
                'ordering': ['order'],
            },
        ),
    ]
