# Generated by Django 6.0.7 on 2026-07-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_sitecontactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('about_us', 'About Us'), ('privacy_policy', 'Privacy Policy'), ('terms_conditions', 'Terms & Conditions')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Leave a blank line between paragraphs.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
